export const posts = [
  {
    id: 1,
    title: 'Stand up Comedy Live at Koramangala',
    description:
      'Comedy Shots presents Wild Comedy Nights. Come on down with friends, family, enemies, random strangers,or by yourself for an absurd, edgy, and funny evening as these Bangalore regulars try to crack you up with their jokes. A stand-up comedy night to remember. Venue: Sat 30 Dec 2023 - Sun 28 Jan 2024',
    location: 'Bengaluru',
    tags_array: ['Comics', 'Jokes', 'Weekends', 'Blr'],
    created_at: '28 Dec 23',
    user_id: 12,
    event_status: 'Upcoming',
    urls: ['../assets/eve1.avif'],
    going_count: 56,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 0,
    dislike_count: 0,
    post_type: 'Events',
    avatar: '../assets/comedy.png',
    username: 'royaleclubblr',
    selected_option: 'going',
    comments: [
      {
        username: 'rookieExplorer',
        id: 15,
        content:
          'Excited to enjoy this for a month.Looking forward to meet you all!!',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'antonydas',
        id: 16,
        content: 'Will this be good a good how to look out for?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Exited for the event?',
      },
      {
        user: 'naveen',
        avatar: '../assets/userimage.png',
        content: 'Hello there!!',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Hey naveen!',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Are you going too?',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'for the event',
      },
    ],
  },
  {
    id: 2,
    title: 'Kanyathon 2023- 2024',
    description:
      'Kanyathon an annual charity run organised by the students of our prestigious IFIM Institutions and JAGSoM is back with its 12th edition this year and the 2nd edition of Kanyathon at Vijaybhoomi University.We as an institution have been giving back to society especially to empower the women of the nation. The mission of Kanyathon is to empower women and girls. We plan to achieve this through our own education centre called KANYATHON SHIKSHA KENDRA. Kanyathon Shiksha Kendra is a skill-building centre established in two of our adopted villages to educate and empower the young generation of rural areas. Kanyathon student team has pledged to use every penny acquired from the charity run for the well-being of women and children of this nation. So participate and help us in this noble cause!!',
    location: 'Bengaluru',
    tags_array: ['charities', 'fundraising', 'bangalore'],
    created_at: '28 Dec 23',
    user_id: 14,
    event_status: 'Upcoming',
    urls: ['../assets/cht.png'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 26,
    like_count: 0,
    dislike_count: 0,
    post_type: 'Charity',
    avatar: '../assets/userimage.png',
    username: 'ifimmgmt',
    selected_option: 'donated',
    comments: [],
    chats: [],
  },
  {
    id: 3,
    title: 'Amazon End-Of-The-Year Sale | 27th - 31st December 2023',
    description: 'Get some amazing offers and savings from Amazon before the year ends. The ultimate year-end sale can be called the "End of the Year Sale". Similar to the Christmas sale, the massive online retailer will grant clients access to items at steep discounts on the occasion of the new year. Save up to 80% on several products. It would not be a good idea to miss this sale.Amazons year-end sale offers everything you could possibly want at unbelievably low prices.This Amazon upcoming sale is expected to start from 27th-31st December 2023.',
    location: 'Bengaluru',
    tags_array: [],
    created_at: '28 Dec 23',
    user_id: 25,
    event_status: '',
    urls: ['../assets/ama1.jpg'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 12,
    dislike_count: 2,
    post_type: 'News',
    avatar: '../assets/userimage.png',
    username: 'royaleclubblr',
    selected_option: 'like',
    comments: [
      {
        username: 'rajesh',
        id: 45,
        content:
          'This news is valid?',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'vignesh',
        id: 75,
        content: 'Where can I know more about this?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [],
  }, {
    id: 4,
    title: 'Ed Sheeran: +–=÷× Tour',
    description: 'We’re ‘Thinking Out Loud’ here, but picture yourself at Ed Sheeran’s LIVE concert! The global sensation is bringing the +–=÷× tour to India for the first time ever (and yes, you can pronounce it as the Mathematics tour!) Celebrating hits from his five albums that we know, love and can’t stop grooving to, this concert offers you a monumental stadium set-up with a centre stage and a mind-blowing experience that is bound to give you the ‘Shivers.’This is Ed Sheeran in India like you’ve never experienced before!So India, get ready for the ‘Perfect Equation’ coming your way!',
    location: 'Bengaluru',
    tags_array: ['Event','music','edsheeran','pop'],
    created_at: '28 Dec 23',
    user_id: 28,
    event_status: '',
    urls: ['../assets/edds.jpg','../assets/edsheeranevent.avif','../assets/edddddd.jpg'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 12,
    dislike_count: 2,
    post_type: 'News',
    avatar: '../assets/userimage.png',
    username: 'royaleclubblr',
    selected_option: 'like',
    comments: [
      {
        username: 'john',
        id: 54,
        content:
          'Excited to see events happening again!!',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'vignesh',
        id: 75,
        content: 'When is the reigstration going to start?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [],
  },{
    id: 1,
    title: 'Stand up Comedy Live at Koramangala',
    description:
      'Comedy Shots presents Wild Comedy Nights. Come on down with friends, family, enemies, random strangers,or by yourself for an absurd, edgy, and funny evening as these Bangalore regulars try to crack you up with their jokes. A stand-up comedy night to remember. Venue: Sat 30 Dec 2023 - Sun 28 Jan 2024',
    location: 'Bengaluru',
    tags_array: ['Comics', 'Jokes', 'Weekends', 'Blr'],
    created_at: '28 Dec 23',
    user_id: 12,
    event_status: 'Upcoming',
    urls: ['../assets/eve1.avif'],
    going_count: 56,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 0,
    dislike_count: 0,
    post_type: 'Events',
    avatar: '../assets/comedy.png',
    username: 'royaleclubblr',
    selected_option: 'going',
    comments: [
      {
        username: 'rookieExplorer',
        id: 15,
        content:
          'Excited to enjoy this for a month.Looking forward to meet you all!!',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'antonydas',
        id: 16,
        content: 'Will this be good a good how to look out for?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Exited for the event?',
      },
      {
        user: 'naveen',
        avatar: '../assets/userimage.png',
        content: 'Hello there!!',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Hey naveen!',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Are you going too?',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'for the event',
      },
    ],
  },
  {
    id: 2,
    title: 'Kanyathon 2023- 2024',
    description:
      'Kanyathon an annual charity run organised by the students of our prestigious IFIM Institutions and JAGSoM is back with its 12th edition this year and the 2nd edition of Kanyathon at Vijaybhoomi University.We as an institution have been giving back to society especially to empower the women of the nation. The mission of Kanyathon is to empower women and girls. We plan to achieve this through our own education centre called KANYATHON SHIKSHA KENDRA. Kanyathon Shiksha Kendra is a skill-building centre established in two of our adopted villages to educate and empower the young generation of rural areas. Kanyathon student team has pledged to use every penny acquired from the charity run for the well-being of women and children of this nation. So participate and help us in this noble cause!!',
    location: 'Bengaluru',
    tags_array: ['charities', 'fundraising', 'bangalore'],
    created_at: '28 Dec 23',
    user_id: 14,
    event_status: 'Upcoming',
    urls: ['../assets/cht.png'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 26,
    like_count: 0,
    dislike_count: 0,
    post_type: 'Charity',
    avatar: '../assets/userimage.png',
    username: 'ifimmgmt',
    selected_option: 'donated',
    comments: [],
    chats: [],
  },
  {
    id: 3,
    title: 'Amazon End-Of-The-Year Sale | 27th - 31st December 2023',
    description: 'Get some amazing offers and savings from Amazon before the year ends. The ultimate year-end sale can be called the "End of the Year Sale". Similar to the Christmas sale, the massive online retailer will grant clients access to items at steep discounts on the occasion of the new year. Save up to 80% on several products. It would not be a good idea to miss this sale.Amazons year-end sale offers everything you could possibly want at unbelievably low prices.This Amazon upcoming sale is expected to start from 27th-31st December 2023.',
    location: 'Bengaluru',
    tags_array: [],
    created_at: '28 Dec 23',
    user_id: 25,
    event_status: '',
    urls: ['../assets/ama1.jpg'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 12,
    dislike_count: 2,
    post_type: 'News',
    avatar: '../assets/userimage.png',
    username: 'royaleclubblr',
    selected_option: 'like',
    comments: [
      {
        username: 'rajesh',
        id: 45,
        content:
          'This news is valid?',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'vignesh',
        id: 75,
        content: 'Where can I know more about this?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [],
  }, {
    id: 4,
    title: 'Ed Sheeran: +–=÷× Tour',
    description: 'We’re ‘Thinking Out Loud’ here, but picture yourself at Ed Sheeran’s LIVE concert! The global sensation is bringing the +–=÷× tour to India for the first time ever (and yes, you can pronounce it as the Mathematics tour!) Celebrating hits from his five albums that we know, love and can’t stop grooving to, this concert offers you a monumental stadium set-up with a centre stage and a mind-blowing experience that is bound to give you the ‘Shivers.’This is Ed Sheeran in India like you’ve never experienced before!So India, get ready for the ‘Perfect Equation’ coming your way!',
    location: 'Bengaluru',
    tags_array: ['Event','music','edsheeran','pop'],
    created_at: '28 Dec 23',
    user_id: 28,
    event_status: '',
    urls: ['../assets/edds.jpg','../assets/edsheeranevent.avif','../assets/edddddd.jpg'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 12,
    dislike_count: 2,
    post_type: 'News',
    avatar: '../assets/userimage.png',
    username: 'royaleclubblr',
    selected_option: 'like',
    comments: [
      {
        username: 'john',
        id: 54,
        content:
          'Excited to see events happening again!!',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'vignesh',
        id: 75,
        content: 'When is the reigstration going to start?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [],
  },{
    id: 1,
    title: 'Stand up Comedy Live at Koramangala',
    description:
      'Comedy Shots presents Wild Comedy Nights. Come on down with friends, family, enemies, random strangers,or by yourself for an absurd, edgy, and funny evening as these Bangalore regulars try to crack you up with their jokes. A stand-up comedy night to remember. Venue: Sat 30 Dec 2023 - Sun 28 Jan 2024',
    location: 'Bengaluru',
    tags_array: ['Comics', 'Jokes', 'Weekends', 'Blr'],
    created_at: '28 Dec 23',
    user_id: 12,
    event_status: 'Upcoming',
    urls: ['../assets/eve1.avif'],
    going_count: 56,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 0,
    dislike_count: 0,
    post_type: 'Events',
    avatar: '../assets/comedy.png',
    username: 'royaleclubblr',
    selected_option: 'going',
    comments: [
      {
        username: 'rookieExplorer',
        id: 15,
        content:
          'Excited to enjoy this for a month.Looking forward to meet you all!!',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'antonydas',
        id: 16,
        content: 'Will this be good a good how to look out for?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Exited for the event?',
      },
      {
        user: 'naveen',
        avatar: '../assets/userimage.png',
        content: 'Hello there!!',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Hey naveen!',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'Are you going too?',
      },
      {
        user: 'rookieExplorer',
        avatar: '../assets/itadori.jfif',
        content: 'for the event',
      },
    ],
  },
  {
    id: 2,
    title: 'Kanyathon 2023- 2024',
    description:
      'Kanyathon an annual charity run organised by the students of our prestigious IFIM Institutions and JAGSoM is back with its 12th edition this year and the 2nd edition of Kanyathon at Vijaybhoomi University.We as an institution have been giving back to society especially to empower the women of the nation. The mission of Kanyathon is to empower women and girls. We plan to achieve this through our own education centre called KANYATHON SHIKSHA KENDRA. Kanyathon Shiksha Kendra is a skill-building centre established in two of our adopted villages to educate and empower the young generation of rural areas. Kanyathon student team has pledged to use every penny acquired from the charity run for the well-being of women and children of this nation. So participate and help us in this noble cause!!',
    location: 'Bengaluru',
    tags_array: ['charities', 'fundraising', 'bangalore'],
    created_at: '28 Dec 23',
    user_id: 14,
    event_status: 'Upcoming',
    urls: ['../assets/cht.png'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 26,
    like_count: 0,
    dislike_count: 0,
    post_type: 'Charity',
    avatar: '../assets/userimage.png',
    username: 'ifimmgmt',
    selected_option: 'donated',
    comments: [],
    chats: [],
  },
  {
    id: 3,
    title: 'Amazon End-Of-The-Year Sale | 27th - 31st December 2023',
    description: 'Get some amazing offers and savings from Amazon before the year ends. The ultimate year-end sale can be called the "End of the Year Sale". Similar to the Christmas sale, the massive online retailer will grant clients access to items at steep discounts on the occasion of the new year. Save up to 80% on several products. It would not be a good idea to miss this sale.Amazons year-end sale offers everything you could possibly want at unbelievably low prices.This Amazon upcoming sale is expected to start from 27th-31st December 2023.',
    location: 'Bengaluru',
    tags_array: [],
    created_at: '28 Dec 23',
    user_id: 25,
    event_status: '',
    urls: ['../assets/ama1.jpg'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 12,
    dislike_count: 2,
    post_type: 'News',
    avatar: '../assets/userimage.png',
    username: 'royaleclubblr',
    selected_option: 'like',
    comments: [
      {
        username: 'rajesh',
        id: 45,
        content:
          'This news is valid?',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'vignesh',
        id: 75,
        content: 'Where can I know more about this?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [],
  }, {
    id: 4,
    title: 'Ed Sheeran: +–=÷× Tour',
    description: 'We’re ‘Thinking Out Loud’ here, but picture yourself at Ed Sheeran’s LIVE concert! The global sensation is bringing the +–=÷× tour to India for the first time ever (and yes, you can pronounce it as the Mathematics tour!) Celebrating hits from his five albums that we know, love and can’t stop grooving to, this concert offers you a monumental stadium set-up with a centre stage and a mind-blowing experience that is bound to give you the ‘Shivers.’This is Ed Sheeran in India like you’ve never experienced before!So India, get ready for the ‘Perfect Equation’ coming your way!',
    location: 'Bengaluru',
    tags_array: ['Event','music','edsheeran','pop'],
    created_at: '28 Dec 23',
    user_id: 28,
    event_status: '',
    urls: ['../assets/edds.jpg','../assets/edsheeranevent.avif','../assets/edddddd.jpg'],
    going_count: 0,
    notgoing_count: 0,
    maybe_count: 0,
    donated_count: 0,
    like_count: 12,
    dislike_count: 2,
    post_type: 'News',
    avatar: '../assets/userimage.png',
    username: 'royaleclubblr',
    selected_option: 'like',
    comments: [
      {
        username: 'john',
        id: 54,
        content:
          'Excited to see events happening again!!',
        avatar: '../assets/itadori.jfif',
        created_at: '28 Dec 23',
      },
      {
        username: 'vignesh',
        id: 75,
        content: 'When is the reigstration going to start?',
        avatar: '../assets/userimage.png',
        created_at: '28 Dec 23',
      },
    ],
    chats: [],
  }
];
