export const posts = [
    {
        id: 1,
        title: "Ed Sheeran in BLR!!!",
        description: "Celebrating hits from his five albums that we know, love and cant stop grooving to, this concert offers you a monumental stadium set-up with a centre stage and a mind-blowing experience that is bound to give you the Shivers. So India, get ready for the Perfect Equation coming your way!",
        location: "Bengaluru",
        tags_array: ['India', 'EdSheeran', ' Event', 'Music', 'EdSheeran', ' Event', 'Music'],
        created_at: "17 Dec 23",
        user_id: 12,
        event_status: 'Ended',
        urls: ["../assets/edsheeranevent.avif","../assets/edsheeranevent.avif","../assets/edds.jpg"],
        going_count: 1,
        notgoing_count: 0,
        maybe_count:0,
        donated_count: 0,
        like_count: 0,
        dislike_count:0,
        post_type: 'Events',
        avatar: '../assets/userimage.png',
        username: 'naveenprasanth',
        selected_option: '',
        comments:[{username: 'naveen', id: 15, content: 'Testing the comment section witth mock data!',avatar:'../assets/userimage.png',created_at:'19 Dec 23'},{username: 'naveen', id: 15, content: 'Testing the comment section witth mock data!',avatar:'../assets/userimage.png',created_at:'19 Dec 23'}]
    }, {
        id: 2,
        title: "Ed Sheeran in BLR!!!",
        description: "Celebrating hits from his five albums that we know, love and cant stop grooving to, this concert offers you a monumental stadium set-up with a centre stage and a mind-blowing experience that is bound to give you the Shivers. So India, get ready for the Perfect Equation coming your way!",
        location: "Bengaluru",
        tags_array: ['India', 'Ed Sheeran', ' Event', 'Music'],
        created_at: "17 Dec 23",
        user_id: 13,
        event_status: 'Ongoing',
        urls: ["../assets/edsheeranevent.avif"],
        going_count: 10,
        donated_count: 0,
        like_count: 0,
        post_type: 'Events',
        avatar: '../assets/userimage.png',
        username: 'prasanth'
    }, {
        id: 2,
        title: "Ed Sheeran in BLR!!!",
        description: "Celebrating hits from his five albums that we know, love and cant stop grooving to, this concert offers you a monumental stadium set-up with a centre stage and a mind-blowing experience that is bound to give you the Shivers. So India, get ready for the Perfect Equation coming your way!",
        location: "Bengaluru",
        tags_array: ['India', 'Ed Sheeran', ' Event', 'Music'],
        created_at: "17 Dec 23",
        user_id: 13,
        event_status: 'Upcoming',
        urls: ["../assets/edsheeranevent.avif"],
        going_count: 10,
        donated_count: 0,
        like_count: 5,
        post_type: 'News',
        avatar: '../assets/userimage.png',
        username: 'prasanth'
    }, {
        id: 2,
        title: "Ed Sheeran in BLR!!!",
        description: "Celebrating hits from his five albums that we know, love and cant stop grooving to, this concert offers you a monumental stadium set-up with a centre stage and a mind-blowing experience that is bound to give you the Shivers. So India, get ready for the Perfect Equation coming your way!",
        location: "Bengaluru",
        tags_array: ['India', 'Ed Sheeran', ' Event', 'Music'],
        created_at: "17 Dec 23",
        user_id: 13,
        event_status: '',
        urls: ["../assets/edsheeranevent.avif"],
        going_count: 10,
        donated_count: 0,
        like_count: 0,
        post_type: 'Events',
        avatar: '../assets/userimage.png',
        username: 'prasanth'
    }, {
        id: 2,
        title: "Ed Sheeran in BLR!!!",
        description: "Celebrating hits from his five albums that we know, love and cant stop grooving to, this concert offers you a monumental stadium set-up with a centre stage and a mind-blowing experience that is bound to give you the Shivers. So India, get ready for the Perfect Equation coming your way!",
        location: "Bengaluru",
        tags_array: ['India', 'Ed Sheeran', ' Event', 'Music'],
        created_at: "17 Dec 23",
        user_id: 13,
        event_status: '',
        urls: ["../assets/edsheeranevent.avif"],
        going_count: 10,
        donated_count: 0,
        like_count: 0,
        post_type: 'Events',
        avatar: '../assets/userimage.png',
        username: 'prasanth'
    }];